### ISSUE TITLE
commentmessage can be too big and fail

### ISSUE THREAD

**Issue by markjm** [github/safe-settings#245]
## Problem Description
There is a limit to comment in checks api summary. When there are a large number of changes (like changing a setting across all repos), this API call can fail, casuing no completion status to ever be posted

### What is actually happening
Check run stays pending

### What is the expected behavior
Check run completes

A simple solution we are using is to just make sure the comment fits in summary limits
![image](https://user-images.githubusercontent.com/16494982/179824071-40b2e8e2-4fad-4fc3-ac8c-1d42c5a9008a.png)
but its not super pretty. I can implenent this solution if we want

**Comment by markjm** [comment]
cc @decyjphr

**Comment by svg153** [comment]
We are experiencing the same bug with pull requests that do not have any safe-settings files.

```
HttpError: Invalid request.

Only 65535 characters are allowed; 66662 were supplied.
    at /opt/safe-settings/node_modules/@octokit/request/dist-node/index.js:86:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async sendRequestWithRetries (/opt/safe-settings/node_modules/@octokit/auth-app/dist-node/index.js:466:12)
    at async Job.doExecute (/opt/safe-settings/node_modules/bottleneck/light.js:405:18)
```

We have more than 20 repositories managed with safe-settings, and now it always fails. Furthermore, we created a workflow (we discuss it [here](https://github.com/github/safe-settings/issues/217#issuecomment-1139554493)) to cancel the status.
