### ISSUE TITLE
TypeError: Cannot read property 'error' of undefined on POST

### ISSUE THREAD

**Issue by jpenagg** [github/safe-settings#314]
## Problem Description
We are seeing the app throw a `TypeError` when any Github event triggers the webhook. The app is running on Kubernetes and deployed with Helm. 

### What is actually happening
The app throws a `500` and doesn't enforce any settings defined in the `admin` repo.

### What is the expected behavior
The app returns a `200` and enforces the settings defined in the `admin` repo.

### Error output, if available

```
AggregateError: 
    TypeError: Cannot read property 'error' of undefined
        at /opt/safe-settings/lib/configManager.js:20:18
        at async ConfigManager.loadYaml (/opt/safe-settings/lib/configManager.js:19:24)
        at async syncAllSettings (/opt/safe-settings/index.js:16:29)
        at async Promise.all (index 0)
        at async middleware (/opt/safe-settings/node_modules/@octokit/webhooks/dist-node/index.js:355:5)
```

## Context
n/a

### Are you using the hosted instance of probot/settings or running your own?
Running my own.

### If running your own instance, are you using it with github.com or GitHub Enterprise?
github.com.

#### Version of probot/settings
`^12.2.8`

#### Version of GitHub Enterprise
n/a

**Comment by arturmartins** [comment]
hello @github team. Any updates on this?

**Comment by decyjphr** [comment]
Hi, You would need a repo called `admin` and in that repo there should be a file with the path `.github/settings.yml`. This is explained [here](https://github.com/github/safe-settings#how-to-use)

Samples of these file are [here](https://github.com/github/safe-settings/tree/main-enterprise/docs/sample-settings)

Please let me know if the file is there.

**Comment by jpenagg** [comment]
@decyjphr Hi, yes the admin repo was already set up at the time and includes the path `.github/settings.yml`.

I've sent the errors to console and here are a few more errors:

```
Error getting settings Error: error:0909006C:PEM routines:get_name:no start line
ERROR (event): Cannot read property 'data' of undefined
    TypeError: Cannot read property 'data' of undefined
        at ConfigManager.loadYaml (/opt/safe-settings/lib/configManager.js:25:34)
        at async syncSettings (/opt/safe-settings/index.js:70:29)
        at async Promise.all (index 0)
        at async middleware (/opt/safe-settings/node_modules/@octokit/webhooks/dist-node/index.js:355:5)

** payload **

INFO (http): POST / 500 - 35ms
    err: {
      "type": "Error",
      "message": "failed with status code 500",
      "stack":
          Error: failed with status code 500
              at ServerResponse.onResFinished (/opt/safe-settings/node_modules/pino-http/logger.js:77:38)
              at ServerResponse.emit (events.js:412:35)
              at ServerResponse.emit (domain.js:470:12)
              at onFinish (_http_outgoing.js:792:10)
              at callback (internal/streams/writable.js:513:21)
              at afterWrite (internal/streams/writable.js:466:5)
              at afterWriteTick (internal/streams/writable.js:453:10)
              at processTicksAndRejections (internal/process/task_queues.js:81:21)
    }
```

**Comment by decyjphr** [comment]
Looking at the error this looks like misconfigured private key. The private key must start with `-----BEGIN RSA PRIVATE KEY-----` and end with `-----END RSA PRIVATE KEY-----` 
The private key is used for authentication and so any API request including the one to get the config would fail due to that.

**Comment by jpenagg** [comment]
Thank you very much @decyjphr, that was it 😄 

For context we are storing the credentials in AWS secrets manager and using the SDK to retrieve it, but the private key was malformed.

We fixed it with: `privateKey: secret.private_key.replace(/\\n/g, '\n')`.

Thanks again! Feel free to close this issue out.
