### ISSUE TITLE
 Error: EISDIR when webhook event is triggered

### ISSUE THREAD

**Issue by davyrod** [github/safe-settings#352]
## Problem Description
Self-hosted deployment of safe settings throwing the following error when a webhook event is received:

`AggregateError: 
    Error: EISDIR: illegal operation on a directory, read
        at loadYamlFileSystem (/opt/safe-settings/index.js:100:41)
        at syncSettings (/opt/safe-settings/index.js:67:32)
        at /opt/safe-settings/index.js:265:12
        at /opt/safe-settings/node_modules/@octokit/webhooks/dist-node/index.js:177:14
        at async Promise.all (index 0)
        at async middleware (/opt/safe-settings/node_modules/@octokit/webhooks/dist-node/index.js:355:5)`

### What is actually happening
Nothing happens, error seems to be blocking the deploymentConfig from being read. 

When listing the `/app/` directory in deployed container, instead of a `deployment-config.yaml` file it is set as a directory.

### What is the expected behavior
`/app/deployment-config.yaml` would be set as a file instead of a directory and safe settings application would receive the webhook event and apply the settings from the `admin` repository.  

### Error output, if available

```
AggregateError: 
    Error: EISDIR: illegal operation on a directory, read
        at loadYamlFileSystem (/opt/safe-settings/index.js:100:41)
        at syncSettings (/opt/safe-settings/index.js:67:32)
        at /opt/safe-settings/index.js:265:12
        at /opt/safe-settings/node_modules/@octokit/webhooks/dist-node/index.js:177:14
        at async Promise.all (index 0)
        at async middleware (/opt/safe-settings/node_modules/@octokit/webhooks/dist-node/index.js:355:5)
```

### Are you using the hosted instance of probot/settings or running your own?
Running our own instance utilizing the helm chart described in the Deployment docs.

### If running your own instance, are you using it with github.com or GitHub Enterprise?
github.com

#### Version of probot/settings
v2.0.17

**Comment by davyrod** [comment]
I figured out the issue is with the helm chart itself.  I patched it in my local environment but submitted the following PR to fix the helm chart.

https://github.com/decyjphr-org/charts/pull/1
