### ISSUE TITLE
AppId not set when using Helm chart

### ISSUE THREAD

**Issue by alexisparis** [github/safe-settings#434]
I tried to deploy Safe-settings on an EKS cluster by using the Helm chart 0.1.0.

```
helm upgrade --install \
            --username="XXX" \
            --password="XXX" \
            safe-settings-test \
            -f values.yml \
            --set appEnv.APP_ID="\"XXX\"" \
            --set appEnv.PRIVATE_KEY="XXX" \
            --set appEnv.WEBHOOK_SECRET="XXX" \
            --set appEnv.DEPLOYMENT_CONFIG_FILE="deployment-settings.yml" \
            --namespace YYY \
            https://enterprise-repo/safe-settings-0.1.0.tgz
```

(using XXX for obfuscation)

We got the following error :

> safe-settings@0.1.0-rc.26 start /opt/safe-settings
> probot run ./index.js

(node:36) UnhandledPromiseRejectionWarning: Error: [@octokit/auth-app] appId option is required
    at Object.createAppAuth (/opt/safe-settings/node_modules/@octokit/auth-app/dist-node/index.js:402:11)
    at getState (/opt/safe-settings/node_modules/octokit-auth-probot/dist-node/index.js:176:21)
    at createProbotAuth (/opt/safe-settings/node_modules/octokit-auth-probot/dist-node/index.js:191:17)
    at new Octokit (/opt/safe-settings/node_modules/@octokit/core/dist-node/index.js:113:20)
    at new _a (/opt/safe-settings/node_modules/@octokit/core/dist-node/index.js:167:30)
    at new OctokitWithDefaults (/opt/safe-settings/node_modules/@octokit/core/dist-node/index.js:143:11)
    at new OctokitWithDefaults (/opt/safe-settings/node_modules/@octokit/core/dist-node/index.js:143:11)
    at new Probot (/opt/safe-settings/node_modules/probot/lib/probot.js:38:25)
    at new ProbotWithDefaults (/opt/safe-settings/node_modules/probot/lib/probot.js:64:17)
    at new Server (/opt/safe-settings/node_modules/probot/lib/server/server.js:36:26)
(Use `node --trace-warnings ...` to show where the warning was created)

I realized that the default docker image version is the 2.0.0 and gave also a try with the 2.0.18, but got the same issue.

It seems that the options are not correctly set but I can clearly see that my pod has the following environments variables : APP_ID, WEBHOOK_SECRET and PRIVATE_KEY with the expected values as defined during helm command execution.

 
Definitely need some help toe troubleshoot this issue :-)

**Comment by L1ghtman2k** [comment]
resolved by https://github.com/decyjphr-org/charts/issues/2?
