### ISSUE TITLE
Safe-Settings GitHub App not working with GHES

### ISSUE THREAD

**Issue by JDunnUKG** [github/safe-settings#484]
Hello,

When configuring [Safe-Settings](https://github.com/github/safe-settings) with our GHES Staging instance, we're finding that after following the deployment instructions the Safe-Settings application throws 500 status codes back to GHES when the it sends a webhook response. Included is the error message generated by the application.

AggregateError: 
    TypeError: Cannot read properties of undefined (reading 'data')
        at ConfigManager.loadYaml (/opt/safe-settings/lib/configManager.js:28:34)
        at async syncAllSettings (/opt/safe-settings/index.js:17:29)
        at async Promise.all (index 0)
        at async middleware (/opt/safe-settings/node_modules/@octokit/webhooks/dist-node/index.js:355:5)

**Comment by JDunnUKG** [comment]
This issue was resolved internally.  Some of the environment variables were not getting included from the .env file while creating the Docker image.
