### ISSUE TITLE
The "Safe-setting validator" in some cases hangs on the PR

### ISSUE THREAD

**Issue by skiff174** [github/safe-settings#501]
## Problem Description

The "Safe-setting validator" in some cases hangs on the PR and never finishes. 

### What is actually happening

Currently the "Safe-setting validator" has the following messages:

- Safe-setting validator 
  Started 1d 2h 55m 57s ago
-  Starting NOP
  initiating...

At the same time, on the GitHub App, on the advanced tab, there is a "check_run" request with the response "500". The error message is below.

### What is the expected behavior

The validator has to respond properly and return the appropriate error message

### Error output, if available

AggregateError: 
    TypeError: Cannot convert undefined or null to object
        at Function.keys (<anonymous>)
        at Settings.getSubOrgConfig (/opt/safe-settings/lib/settings.js:264:28)
        at Settings.updateRepos (/opt/safe-settings/lib/settings.js:196:31)
        at runMicrotasks (<anonymous>)
        at runNextTicks (node:internal/process/task_queues:61:5)
        at listOnTimeout (node:internal/timers:528:9)
        at processTimers (node:internal/timers:502:7)
        at async Promise.all (index 3)
        at async Function.syncSubOrgs (/opt/safe-settings/lib/settings.js:21:5)
        at async Promise.all (index 0)

```

```

### Are you using the hosted instance of probot/settings or running your own?

- We are running our own instance of the Safe-Settings app

### If running your own instance, are you using it with github.com or GitHub Enterprise?

- We are utilizing it with github.com

#### Version of settings

"version": "0.1.0-rc.26"(In the package.json file)

#### Version of GitHub Enterprise

- N/A

**Comment by Alex-Mills-seccl** [comment]
I am experiencing the same issue. 

I can go to the App settings, and click Advanced to see the payload of the timed-out request, and press redeliver.
Redeliver resets the timer on the Safe-settings-validator, but still times out.

**Comment by veronluc-ansys** [comment]
Same issue here. Any update?
