### ISSUE TITLE
Error when modify team

### ISSUE THREAD

**Issue by ghost** [github/safe-settings#515]
## Problem Description
When I added team to project I get 500 error in webhook.

### What is actually happening

All web hooks that have team payload either adding team to project or updating team.

### What is the expected behavior

success response 200.

### Error output, if available

```
AggregateError: 
    TypeError: Cannot read properties of undefined (reading 'data')
        at ConfigManager.loadYaml (/opt/safe-settings/lib/configManager.js:28:34)
        at async syncSettings (/opt/safe-settings/index.js:71:29)
        at async Promise.all (index 0)
        at async middleware (/opt/safe-settings/node_modules/@octokit/webhooks/dist-node/index.js:355:5)
```
<img width="821" alt="image" src="https://github.com/github/safe-settings/assets/119829443/d6b8d788-8ec2-4ed3-816b-f6594e47829a">

### Are you using the hosted instance of probot/settings or running your own?

Yes on ec2 with Docker compose.

### If running your own instance, are you using it with github.com or GitHub Enterprise?
github.com 

#### Version of probot/settings

Deployed `master-enterprise` branch

**Comment by zelig81** [comment]
you have to have:
- `deployment-settings.yml` in the folder `/opt/safe-settings/` (or use DEPLOYMENT_CONFIG_PATH variable that points to a new place with the file
- `settings.yml` in repo `admin/.github` or change the ADMIN_REPO env var to point to other repo (and this org level yaml should not be empty - https://github.com/github/safe-settings/issues/467)
