### ISSUE TITLE
Safe Settings doesn't run with just repos

### ISSUE THREAD

**Issue by bheemvennapureddy** [github/safe-settings#572]
safesettings doesn't run with just using the repo/*.yml which means removing settings.yml and deployment-settings.yml
<img width="1199" alt="Screenshot 2023-12-15 at 2 27 27 PM" src="https://github.com/github/safe-settings/assets/144472943/0d464582-4701-4341-8629-764dc51f6b26">
<img width="1137" alt="Screenshot 2023-12-15 at 2 27 46 PM" src="https://github.com/github/safe-settings/assets/144472943/0600343f-6eb1-4c43-8e14-b84b63b31c2e">

**Comment by bheemvennapureddy** [comment]
@svg153  @decyjphr am i doing anything wrong ?

**Comment by bheemvennapureddy** [comment]
<img width="838" alt="Screenshot 2023-12-15 at 2 44 31 PM" src="https://github.com/github/safe-settings/assets/144472943/aa5524df-76f7-406c-b09d-1b023f9f15ba">

**Comment by decyjphr** [comment]
It is coded to expect the _settings.yml_ so it probably ends up as an error.

**Comment by bheemvennapureddy** [comment]
@decyjphr so we can't just rely on the repo's configuration and ignore the org config ?

**Comment by svg153** [comment]
> @decyjphr so we can't just rely on the repo's configuration and ignore the org config ?

It might be interesting to have a feature flag.  Aren't you interested in having general configurations that apply to all repositories?  or what is the reason?  to know, curiosity

**Comment by bheemvennapureddy** [comment]
each team has different reasons to have diff policies but i should be able to manage repo level policies

**Comment by bheemvennapureddy** [comment]
What ever we have in the precedence order should be able to maintain them independently

**Comment by bheemvennapureddy** [comment]
Looks like i also always need base branch protection rule without that i see this error 

`t;,&quot;x-ratelimit-reset&quot;:&quot;1702965036&quot;,&quot;x-ratelimit-resource&quot;:&quot;core&quot;,&quot;x-ratelimit-used&quot;:&quot;443&quot;,&quot;x-xss-protection&quot;:&quot;0&quot;},&quot;data&quot;:{&quot;message&quot;:&quot;Invalid request.\\n\\nNo subschema in \\&quot;anyOf\\&quot; matched.\\nNo subschema in \\&quot;oneOf\\&quot; matched.\\nNot all subschemas of \\&quot;allOf\\&quot; matched.\\nFor &#39;anyOf/1&#39;, {\\&quot;contexts\\&quot;=&gt;[\\&quot;build\\&quot;, \\&quot;codecov/patch\\&quot;, \\&quot;validate_work_item\\&quot;, \\&quot;actions\\&quot;]} is not a null`

**Comment by bheemvennapureddy** [comment]
@svg153 @decyjphr  any thoughts here ?

**Comment by svg153** [comment]
> Looks like i also always need base branch protection rule without that i see this error
> 
> `t;,&quot;x-ratelimit-reset&quot;:&quot;1702965036&quot;,&quot;x-ratelimit-resource&quot;:&quot;core&quot;,&quot;x-ratelimit-used&quot;:&quot;443&quot;,&quot;x-xss-protection&quot;:&quot;0&quot;},&quot;data&quot;:{&quot;message&quot;:&quot;Invalid request.\\n\\nNo subschema in \\&quot;anyOf\\&quot; matched.\\nNo subschema in \\&quot;oneOf\\&quot; matched.\\nNot all subschemas of \\&quot;allOf\\&quot; matched.\\nFor &#39;anyOf/1&#39;, {\\&quot;contexts\\&quot;=&gt;[\\&quot;build\\&quot;, \\&quot;codecov/patch\\&quot;, \\&quot;validate_work_item\\&quot;, \\&quot;actions\\&quot;]} is not a null`

I do not have any protect rule in my test org and works correctly: https://github.com/svg153-org/admin/blob/main/.github/settings.yml

**Comment by decyjphr** [comment]
> [@svg153](https://github.com/svg153) [@decyjphr](https://github.com/decyjphr) any thoughts here ?

I tried to run a test without the _settings.yml_ and I see that [this](https://github.com/github/safe-settings/blob/666209174f06aaafecf3d92dfe4013986b0b4c5c/index.js#L72) line throws an error `TypeError: Cannot read properties of undefined (reading 'data')
    at ConfigManager.loadYaml (/Users/decyjphr/projects/node/probot/safe-settings-oct-31/lib/configManager.js:28:34)
    at async syncSettings (/Users/decyjphr/projects/node/probot/safe-settings-oct-31/index.js:72:29)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async middleware (/Users/decyjphr/projects/node/probot/safe-settings-oct-31/node_modules/@octokit/webhooks/dist-node/index.js:355:5) {stack: 'TypeError: Cannot read properties of undefine…s/@octokit/webhooks/dist-node/index.js:355:5)', message: 'Cannot read properties of undefined (reading 'data')'}`

I am guessing that we'll need to fix this piece of code to ignore the file not being there and provide a empty object there.

Would you be able to modify this code? Or I can take a look at this later this week.

**Comment by bheemvennapureddy** [comment]
> > [@svg153](https://github.com/svg153) [@decyjphr](https://github.com/decyjphr) any thoughts here ?
> 
> I tried to run a test without the _settings.yml_ and I see that [this](https://github.com/github/safe-settings/blob/666209174f06aaafecf3d92dfe4013986b0b4c5c/index.js#L72) line throws an error `TypeError: Cannot read properties of undefined (reading 'data') at ConfigManager.loadYaml (/Users/decyjphr/projects/node/probot/safe-settings-oct-31/lib/configManager.js:28:34) at async syncSettings (/Users/decyjphr/projects/node/probot/safe-settings-oct-31/index.js:72:29) at async Promise.all (index 0) at async Promise.all (index 0) at async middleware (/Users/decyjphr/projects/node/probot/safe-settings-oct-31/node_modules/@octokit/webhooks/dist-node/index.js:355:5) {stack: 'TypeError: Cannot read properties of undefine…s/@octokit/webhooks/dist-node/index.js:355:5)', message: 'Cannot read properties of undefined (reading 'data')'}`
> 
> I am guessing that we'll need to fix this piece of code to ignore the file not being there and provide a empty object there.
> 
> Would you be able to modify this code? Or I can take a look at this later this week.

https://github.com/github/safe-settings/pull/576 is this what you mean ?
